// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/protonum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message {

  /// <summary>Holder for reflection information generated from proto/protonum.proto</summary>
  public static partial class ProtonumReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/protonum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtonumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRwcm90by9wcm90b251bS5wcm90bxIHbWVzc2FnZSosCghQcm90b051bRIL",
            "CgdVbmtub3duEAASEwoOQ01Mb2dpblJlcXVlc3QQ6QdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Message.ProtoNum), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 消息头枚举，不用于消息收发
  /// !!! 名字必须对应到消息类型
  /// </summary>
  public enum ProtoNum {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    [pbr::OriginalName("CMLoginRequest")] CmloginRequest = 1001,
  }

  #endregion

}

#endregion Designer generated code
